### ISSUE TITLE
这个代理会被墙吗？是只适用于个别使用，还是广为传播？

### ISSUE THREAD

**Issue by begood0513** [gfw-breaker/open-proxy#10]

**Comment by gfw-breaker** [comment]
是给广大不会翻墙的网友用的。初期效果非常好，但后来有网警值守屏蔽。
https://github.com/gfw-breaker/banned-news 这个屏蔽不了，但没有视频新闻。

**Comment by kilvn** [comment]
密码dongtaiwang.com，你是自由门的？轮子宣传家？

**Comment by qq435672196** [comment]
> 是给广大不会翻墙的网友用的。初期效果非常好，但后来有网警值守屏蔽。
> https://github.com/gfw-breaker/banned-news 这个屏蔽不了，但没有视频新闻。

你傻逼东西吃你妈的奶逼水去吧，滚你妈的畜生，操你妈的臭逼！老子把你妈吊起来吊打阴道，老子把他妈毛毛虫放进你妈的阴道里面，生出你个杂种，操你妈的臭逼！ 滚！

**Comment by dennis-ritschie** [comment]
fuqcjp

From: qq435672196
Sent: Sunday, 2 August 2020 13:33
To: gfw-breaker/open-proxy
Reply To: gfw-breaker/open-proxy
Cc: Subscribed
Subject: Re: [gfw-breaker/open-proxy] 这个代理会被墙吗？是只适用于个别使用，还是广为传播？ (#10)


你傻逼东西吃你妈的奶逼水去吧，滚你妈的畜生，操你妈的臭逼！老子把你妈吊起来吊打阴道，老子把他妈毛毛虫放进你妈的阴道里面，生出你个杂种，操你妈的臭逼！ 滚！

这是你们这个流氓团伙的常用语

**Comment by pandawiki** [comment]
> <a href="https://github.com/gfw-breaker"><b>@gfw-breaker</a>:</b>
> 是给广大不会翻墙的网友用的。初期效果非常好，但后来有网警值守屏蔽。
> https://github.com/gfw-breaker/banned-news 这个屏蔽不了，但没有视频新闻。

> <a href="https://github.com/pandawiki"><b>@pandawiki</a>:</b>
**你傻逼东西吃你妈的奶逼水去吧，滚你妈的畜生，操你妈的臭逼！老子把你妈吊起来吊打阴道，老子把他妈毛毛虫放进你妈的阴道里面，生出你个杂种，操你妈的臭逼！滚！**

**Comment by dennis-ritschie** [comment]
‎pandawiki watch your face


@pandawiki<https://github.com/pandawiki>:
你傻逼东西吃你妈的奶逼水去吧，滚你妈的畜生，操你妈的臭逼！老子把你妈吊起来吊打阴道，老子把他妈毛毛虫放进你妈的阴道里面，生出你个杂种，操你妈的臭逼！滚！
