### ISSUE TITLE
nginx 权限问题

### ISSUE THREAD

**Issue by MassSmith** [gfw-breaker/open-proxy#9]
centos 6 安装到最后，显示：
nginx: [emerg] mkdir() "/usr/local/nginx/content/cache/epochtimes" failed (13: Permission denied)
nginx: configuration file /etc/nginx/nginx.conf test failed

不成功。有点晕了，我用debian多，这个centos 没用过，看样子是权限的问题，但是不知道从哪里改。nginx也熟悉。用Caddy比较多。

**Comment by MassSmith** [comment]
这个问题终于找到原因了，是selinux的问题，关闭了，就可以正常运行起来了。

**Comment by MassSmith** [comment]
怎么没有youtube了？我想配置youtube-stream。

**Comment by gfw-breaker** [comment]
@MassSmith  YouTube主页经常变动，容易失效，懒得维护了

**Comment by MassSmith** [comment]
我主要的目的就是想转发一些youtube上的小视频，原来是用you2php,但是这个看的人多了，google api容易失效。所以，才研究这个。刚才用你历史库中找到了youtube配置，视频可以打开了。不过似乎旁边的内容，没有了，回头再研究一下，精简页面。我是想如果能把视频转发出去，就可以了，不需要太多的功能。真相传媒有很多视频做的很好，时间正好，几分钟的。国内的人很喜欢这种。

**Comment by MassSmith** [comment]
我觉得其实不用按youtube的原主页设计，自己做一个极简要的主页。我自己琢磨琢磨。
